export class OptionModel {
    constructor (
    public lastPrice:number,
    public lastPriceFrom: number,
    public lastPriceTo: number,
    public symbol:string,
    public marketCapFrom:string,
    public marketCapTo:string,
    public moneyessFrom: number,
    public moneyessTo: number,
    public exchange1:boolean,
    public exchange2:boolean,
    public exchange3:boolean,
    public strikeFrom:number,
    public strikeTo:number,
    public daysToExpFrom:number,
    public daysToExpTo:number,
    public monthlyExp:boolean,
    public weeklyExp:boolean,
    public lastTradeType:number,
    public lastTradeVal:number,
    public secStock:boolean,
    public secNonStock:boolean,
    public secEtf:boolean,
    public secIndex:boolean,
    public optCall:boolean,
    public optPut:boolean,
    public optVolFrom:number,
    public  optVolTo:number,
    public optOpIntFrom:number,
    public optOpIntTo:number,
    public bid:number,
    public bidVal:number,
    public ratioFrom:number,
    public ratioTo:number
    ){}
}
