export class OptionModel {
    constructor (
    public lastPrice:number,
    public moneyessFrom: number,
    public moneyessTo: number,
    public exchange1:boolean,
    public exchange2:boolean,
    public exchange3:boolean,
    public strikeFrom:number,
    public strikeTo:number,
    public daysToExpFrom:number,
    public daysToExpTo:number,
    public monthlyExp:boolean,
    public weeklyExp:boolean,
    public lastTradeType:number,
    public lastTradeVal:number,
    public secStock:boolean,
    public secNonStock:boolean,
    public secEtf:boolean,
    public secIndex:boolean,
    public optCall:boolean,
    public optPut:boolean,
    public bid:number,
    public optOpIntFrom:number,
    public ratioTo:number,
    public lastPriceFrom:number,
    public lastPriceTo:number,
    public optVolFrom:number,
    public optOpIntTo?:number| null,
    public optVolTo?:number| null,
    public ratioFrom?:number| null,
    public symbol?:string| null,
    public marketCapFrom?:string| null,
    public marketCapTo?:string| null
    ){}
}
